### ISSUE TITLE
NX_Firmware 18.1.0 can not use daybreak to update

### ISSUE THREAD

**Issue by BigBu11** [THZoria/NX_Firmware#4] opened 2024-08-31 11:32 UTC
Daybreak display error information is 
Directory /Firmware 18.1.0
Failed to get update information.
Result: 0x00234a02

**Comment by THZoria** [comment] 2024-08-31 11:52
rebootless or classic 18.1.0?

**Comment by impeeza** [comment] 2024-08-31 22:22
Sorry to inform you: that firmware has been out since July 2 and nobody had problem with it,  I have upgraded 56 consoles using that file.

please re-download and check the file, the checksums are:

18.1.0 SHA256:
5a033164f0b908dc7db8202d5403a380ab38d33c38a2f6e276d67b4e60533305

18.1.0 re-bootless SHA256:
a7ae2e2ab35ae1f839d8760cc542f50b0a5336df6c085e86fae564fc84abb80c

**Comment by 3lit3hax** [comment] 2024-09-05 19:27
having the same issue here, i am trying to upgrade from 16.0.0 -> 18.1.0. I have verified your SHA256 codes, and everything looks good. I am using the non-rebootless update. Daybreak just gives me the same error upon selecting the directory containing my update files.

**Comment by THZoria** [comment] 2024-09-05 19:34
![image](https://github.com/user-attachments/assets/0abc1220-c952-46ff-9bab-d5749a21daf7)

Test on my Switch Lite which was still on fw 15.X to 18.1.0 rebootless update
I don't really understand why you have these errors.
A par vous invite à faire un fix archiv bit dans Hekate : Tools ➜ Arch bit - RCM Touch - Pkg1/2 (bottom right) ➜ Fix Archive Bit

**Comment by 3lit3hax** [comment] 2024-09-05 19:39
I have already tried to fix my archived bit, but every time it runs, it says there are no problems. I am on the macOS dev beta, which is likely the problem.

**Comment by THZoria** [comment] 2024-09-05 19:42
If the console is connected to the Internet with anti-ban protection you can use our homebrew, which allows firmware updates via this repo without a PC. 
https://github.com/PoloNX/AtmoPackUpdater/releases/download/2.0.1/AtmoPackUpdater.nro

**Comment by 3lit3hax** [comment] 2024-09-05 19:44
I found the issue, I am assuming macOS 15.0 beta changed how their dot files are created/stored, and Hekate has not updated support to clean these files.

I ran the dot_clean /Volumes/SD command in the terminal to clean the dot files, and now Daybreak is recognizing my firmware. Thanks for the help.

**Comment by THZoria** [comment] 2024-09-05 19:45
Nice
As I'm on MacOS now, this will be very useful.

**Comment by impeeza** [comment] 2024-09-05 22:52
So the problem is a bad OS messing up with your files!

Hekate should not need to clean your files because good OSes shouldn't mess your files.

Please close this issue.

**Closed** 2024-09-05 22:55 UTC
